### ISSUE TITLE
no English translation

### ISSUE THREAD

**Issue by patricus3** [mzdk100/rigela#5]
hello.
I want to try this screenreader, but there's no English translation, could you consider making one?

**Comment by mzdk100** [comment]
We are a friendly English translator, you can use it directly.

**Comment by mzdk100** [comment]
[English README](https://github.com/mzdk100/rigela/blob/master/README-EN.md)

**Comment by patricus3** [comment]
I don’t want to build it but run from release like a person that dislikes rust would..

**Comment by mzdk100** [comment]
[Click here to download](http://rigela.site/rigela/rigela_x64/rigela-main.exe)

**Comment by mzdk100** [comment]
After starting rigela, you will see a welcome window. Find "设置" in the tab, press enter, then find the "选择语言" combo box, use the arrow keys to select the first option, and then restart the rigela program.

**Comment by patricus3** [comment]
Herę are my suggestions after meddling with the screenreader:
1. in notepad, if there’s just blank line, say blank because it’s confusing if it’s silent.
2. Tell me the type of controller I’m focused on.
3. Why the heck I can’t choose an other sapi voice than Microsoft’s?
4. The task manager doesn’t read.

**Comment by mzdk100** [comment]
Thank you for your suggestion. We have released a new version that has improved the English translation and fixed the issue with the default language#6
You can download again to experience it.
We will close this issue, but if you have any further questions, you can reopen it.
